FROM ubuntu:22.04

WORKDIR /app

RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y \
    python3=3.10.6-1~22.04.1 \
    python3-pip=22.0.2+dfsg-1ubuntu0.5 \
    python3-tk=3.10.8-1~22.04 \
    xvfb=2:21.1.4-2ubuntu1.7~22.04.12 \
    wget=1.21.2-2ubuntu1.1 && \
    wget -q https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb && \
    apt-get install -y ./google-chrome-stable_current_amd64.deb && \
    rm google-chrome-stable_current_amd64.deb

COPY requirements_tester.txt requirements.txt

RUN pip3 install -r requirements.txt

COPY tests ./tests

CMD ["python3", "-m", "http.server", "3000"]