version: "3.5"

services:
  app:
    restart: always
    build:
      dockerfile: Dockerfile_app
    ports:
      - "127.0.0.1:${WEB_SERVER_PORT}:${WEB_SERVER_PORT}"
      - "127.0.0.1:2222:22"
    deploy:
      resources:
        limits:
          cpus: "3"

  tester:
    restart: always
    build:
      dockerfile: Dockerfile_tester
    env_file:
      - ./.env